### ISSUE TITLE
Missing error line information

### ISSUE THREAD

**Issue by albertvila** [s-shin/linter-perl#16]
Hi

I'm having some issues with this package. I've attached an image to better show my problems. 

When the perl code has some errors, it does not display the error line, neither the file. And on the code window, I don't get error suggestions on the fly neither the red bullet on the left side of the line.

I don't know if this features are supposed to work here, but I was expecting the same behavior as shown on the linter package.

Thanks

![perl_linter](https://cloud.githubusercontent.com/assets/688206/9523646/4c263b16-4cdb-11e5-9327-6198248b3253.png)

**Comment by s-shin** [comment]
Thank you for reporting.

> When the perl code has some errors, it does not display the error line, neither the file. And on the code window, I don't get error suggestions on the fly neither the red bullet on the left side of the line.

You're right! It seems to be a bug :bug:.
I'll check and fix it!
