### ISSUE TITLE
Multiple Project Support?

### ISSUE THREAD

**Issue by carlosfrodriguez** [s-shin/linter-perl#19]
Hi @s-shin,

I'm trying to switch from SublimeText to Atom, one of the things that I need is the possibility to add different paths to the linter depending on the project i'm opening is there any possibility to do this?

((enjoy))
cr

**Comment by s-shin** [comment]
> I'm trying to switch from SublimeText to Atom

sounds good ;-)

> add different paths to the linter depending on the project i'm opening is there any possibility to do this?

Maybe you can realize that kind of things by using packages such as [project-manager](https://atom.io/packages/project-manager).
This package itself supports [multi-folder projects](http://blog.atom.io/2015/04/15/multi-folder-projects.html) but not does multiple configurations.

I hope this will help you!

**Comment by carlosfrodriguez** [comment]
Let me explain better.

I have some projects (framework) that includes different cpan modules in their release so the users does not need to install all cpan modules that are required, but the included cpan modules varies from project to project and projects are in different paths.

To make it worst I also have plugin modules that uses some modules defined on a framework (the projects mention above)

So I think that add all paths will not work as they are relative to the root directory.

Any idea on how to configure the linter to be capable of include the different modules (so they don't mark as errors as they are nt defined in @Inc)?

Or better... any way to skip the 'use' pragmas?

**Comment by s-shin** [comment]
Sorry I may not understand your intention completely, but

> how to configure the linter to be capable of include the different modules

generally speaking, the best way to manage modules of each project is using [carton](https://github.com/perl-carton/carton), which is just bundler in Ruby, and this package supports it! (also see [settings](https://github.com/s-shin/linter-perl#settings))

Cannot carton resolve your concern?
