### ISSUE TITLE
B::Lint is deprecated

### ISSUE THREAD

**Issue by harpchad** [s-shin/linter-perl#21]
B::Lint is deprecated as of 5.18 and removed in 5.20.  I think it could be built from cpan, but perhaps perl::critic or perl::lint could be used instead?

**Comment by s-shin** [comment]
> B::Lint is deprecated as of 5.18 and removed in 5.20.

Oh, it is a sad news :cry: 

I found two ways to go ahead in your advice and my research:

1. Use [B::Lint module](https://metacpan.org/pod/B::Lint).
  * Easiest way. Users must install B::Lint module globally.
  * The code of linter-perl can be left as it is?
2. Use alternative lint tools such as [Perl::Critic](https://metacpan.org/pod/Perl::Critic) (mature?) or [Perl::Lint](https://metacpan.org/pod/Perl::Lint) (faster?).
  * What is the best may be to introduce pluggable mechanism; we can choose a favorite linter tools and apply a lint configuration properly in some way.
  * I will need to research more about how to run and configure lint.
  * However looking for other linter plugins, they are divided by each linter tool? (e.g. linter-jshint, linter-eslint, ...)

I will keep thinking about this.
Any idea is welcome.

**Comment by s-shin** [comment]
A linter plugin using Perl::Critic is already [here](https://atom.io/packages/linter-perlcritic).
Also one using Perl::Lint will be created someday.
So I concluded this package should focus on B::Lint.

I will implement the code that looks up B::Lint and shows an alert if it is not installed.

**Comment by s-shin** [comment]
https://github.com/s-shin/linter-perl/releases/tag/v0.7.0

**Comment by nonnymoose** [comment]
@harpchad @s-shin On Perl v5.22.1, the version installed on my system, B::Lint fails to build and/or install. (Just to let you know)
Because of this, your package is unlikely to work on Ubuntu 16.04 or beyond.

**Comment by s-shin** [comment]
@nonnymoose 

> On Perl v5.22.1, the version installed on my system, B::Lint fails to build and/or install.

It can be caused by [this issue](https://rt.cpan.org/Public/Bug/Display.html?id=101115).
Skipping test (e.g. `cpanm B::Lint --force`) may resolve the installation problem.

**Comment by nonnymoose** [comment]
Oh. *Facepalm* I should have googled the error. Sorry to poke a closed
issue.
