### ISSUE TITLE
B::Lint not found

### ISSUE THREAD

**Issue by albertvila** [s-shin/linter-perl#25]
Hi

Atom keeps complaining about missing B::Lint package. It happens from the last linter-perl update to version 0.7.0. My Atom version is 1.2.2

"
B::Lint not found.
You should make sure to install B::Lint.
From 5.20, B::Lint is removed from core modules.
"

However, I already have the last B::Lint module version:

B::Lint is up to date. (1.20)

I'm running ubuntu and my perl version is perl 5, version 20, subversion 2 (v5.20.2) built for x86_64-linux-gnu-thread-multi

Any help will be appreciate

Regards

**Comment by elich** [comment]
Hello,
having the same issue I have done some investigation and it is related to linter-perl using perldoc to detect if B::Lint is present on your system.

A simple solution for current version is to install perl-doc package.
To install on Ubuntu run: `sudo apt-get install perl-doc`

Possible solution for future versions is to drop dependency on perldoc.
A little change in linter-perl.coffee should be sufficient.
Something like this should work:
  ```
buildCommandToCheckBLint: (rootDirectory) ->
    [command, args...] = @enhancePerlCommand \
      ["perl", "-MB::Lint", "-e", "1"], rootDirectory
    {command, args}
```

**Comment by albertvila** [comment]
I confirm that installing the perl-doc fixed the problem.

Thanks

**Comment by s-shin** [comment]
@elich Thank you for your investigation.
I forgot the possibility that there are environments in which perldoc isn't installed :persevere:
I will hotfix it with your suggestion.

@albertvila Thanks, your report & confirmation help me very much.

**Comment by novitch** [comment]
Hi,
Having the same issue. I looked into linter-perl.coffee and there is the change that @elich mentionned.

**Comment by pabloab** [comment]
Recently installed linter-perl 0.8.0

![image](https://user-images.githubusercontent.com/657836/27996777-0c2d68c8-64c0-11e7-92d5-ffd751f12373.png)

Perl 5.22.1, Ubuntu 16.04.2, Atom 1.13.1, Electron: 1.3.13, Chrome 52.0.2743.82, Node 6.5.0. _perl-doc is already the newest version (5.22.1-9)_
Probably should be reopened.

**Comment by s-shin** [comment]
@pabloab 
I understood that the linter would change the appearance of the error message on linting.
OK, I will try to make it better. (cf. https://github.com/s-shin/linter-perl/issues/36)

However, the essential reason of this error must be that `B::Lint` isn't installed in your environment as the image you attached says. If you run `perl -MB::Lint -e 1` and get an error, you will have to manually install `B::Lint` (e.g. [`cpanm B::Lint --force`](https://github.com/s-shin/linter-perl/issues/21#issuecomment-310346399)).

**Comment by pabloab** [comment]
I've just installed with `sudo cpan B::Lint` but: 
[...]
```
Test Summary Report
-------------------
t/lint.t (Wstat: 0 Tests: 29 Failed: 1)
  Failed test:  27
Files=1, Tests=29,  1 wallclock secs ( 0.02 usr  0.00 sys +  0.81 cusr  0.07 csys =  0.90 CPU)
Result: FAIL
Failed 1/1 test programs. 1/29 subtests failed.
Makefile:824: recipe for target 'test_dynamic' failed
make: *** [test_dynamic] Error 255
  RJBS/B-Lint-1.20.tar.gz
  /usr/bin/make test -- NOT OK
//hint// to see the cpan-testers results for installing this module, try:
  reports RJBS/B-Lint-1.20.tar.gz
```
And now the console error is slightly different: 
![image](https://user-images.githubusercontent.com/657836/28020235-f781cf78-6559-11e7-8b23-bccfc62859c3.png)

**Comment by s-shin** [comment]
Yes, since `B::Lint` currently has [a bug](https://rt.cpan.org/Public/Bug/Display.html?id=101115) in test, the installation failed.
Giving `-f` option to cpan command may resolve this.

**Comment by pabloab** [comment]
OK, I was reticent to force the installation. Now seems to work...  Nonetheless I suggest to reopen this issue.
I have my module on current directory and everything works fine... but B::Lint complain "Can't locate Mymodule.pm in @INC". `perl -V` show "." is there in @INC. Maybe something to do with forcing the installation?

**Comment by s-shin** [comment]
> Maybe something to do with forcing the installation?

Perhaps, no.

I guess your modules aren't  located in the root (or `lib` directory) of the current [project folder](http://flight-manual.atom.io/getting-started/sections/atom-basics/#opening-directories), and if so, you should modify `incPathsFromProjectRoot` in the [settings](http://flight-manual.atom.io/using-atom/sections/atom-packages/#package-settings).

**Comment by pabloab** [comment]
Wasn't on project folder but on same folder as the `.pl` file.
I'm not sure why but I could get rid of it inserting this two line before calling my module:
```Perl
use FindBin;
use lib $FindBin::Bin;
```

**Comment by s-shin** [comment]
Lint command always runs in the root of the project folder.

For example, when the following project exists:

```
foo-project/
  .git # etc.
  bar-dir/
    fizz-script.pl # including `use BuzzModule;`
    BuzzModule.pm
```

the lint command for `bar-dir/fizz-script.pl` will be `perl -MOLint -I. -Ilib bar-dir/fizz-script.pl` by default settings, so that `bar-dir` isn't included in `@INC`.

> I'm not sure why but I could get rid of it inserting this two line before calling my module:
> ```pl
> use FindBin;
> use lib $FindBin::Bin;
> ```

By this code, the directory of `fizz-script.pl` (= `bar-dir`) is appended to `@INC` and the script will work fine.
