### ISSUE TITLE
executablePath option is ignored

### ISSUE THREAD

**Issue by zostay** [s-shin/linter-perl#28]
Execute Command Via Shell doesn't work for me for some reason. It looks like a problem with Mac OS X's path_helper command, which I don't really find too helpful, actually.

Anyway, while trying to figure that out, I was digging around in the source for this and I'm not sure the executablePath option is being used at all. When I set that option and turn off exectuteCommandViaShell to my plenv shims, the command it calls is just "perl" as per usual. It looks like buildCommand or enhancePerlCommand probably need to be updated to use this option.

**Comment by s-shin** [comment]
I see, you are right.
I knew the new linter (v1.x.x) drop what are related to command execution, but I forgot to care this option (only do rename though).
Thank you for reporting :-)
