### ISSUE TITLE
B::Lint not found 

### ISSUE THREAD

**Issue by Odud** [s-shin/linter-perl#34]
> You should make sure to install B::Lint. From 5.20, B::Lint is removed from core modules.

I'm running Strawberry Perl 5.20.1 on Windows 10. B::Lint is installed but linter-perl isn't finding it for some reason. This started happening after the latest upgrade to version 0.8.0 I think

```
cpan> i B::Lint
Fetching with LWP:
http://cpan.strawberryperl.com/authors/id/R/RJ/RJBS/CHECKSUMS
Module id = B::Lint
    CPAN_USERID  RJBS (Ricardo SIGNES <rjbs@cpan.org>)
    CPAN_VERSION 1.20
    CPAN_FILE    R/RJ/RJBS/B-Lint-1.20.tar.gz
    UPLOAD_DATE  2014-10-26
    MANPAGE      B::Lint - Perl lint
    INST_FILE    C:\Strawberry\perl\site\lib\B\Lint.pm
    INST_VERSION 1.20
cpan>
```

**Comment by Odud** [comment]
Forgot to show the config:
`  "linter-perl":
    executablePath: "c:\\strawberry\\perl\\bin"`

**Comment by SrMixAlot** [comment]
Just a guess, but maybe try copying c:\Strawberry\perl\site\lib\B\ directory to c:\Strawberry\perl\lib

**Comment by Odud** [comment]
Made no changes other than to update linter to 1.11.18 and then reinstall
linter-perl (0.8.0) and all is working fine. So I'm puzzled as to what
fixed the issue, but happy that it has gone away. Thanks for your help.

*Pete Barlow*
